### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null

### ISSUE THREAD

**Issue by VacAge** [Geitenijs/CommandBlocks#19]
**Describe the bug**
does not see the command of another plugin

**To Reproduce**
1. Create a command via MyCommand
2. set     commands: - console: - command
3. [See error](https://mclo.gs/2ZYIAi7)

**Expected behavior**
Executing a command

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 64
 - purpurmc
 - 1.20.1
 - Configs
![MyCommand](https://github.com/Geitenijs/CommandBlocks/assets/55461273/a3d0b00b-0756-4d6b-a5b2-e11f803ecd4f)
![CommandBlocks](https://github.com/Geitenijs/CommandBlocks/assets/55461273/9717b8e3-3637-4b0a-8567-f39eff8b935c)

**Comment by Geitenijs** [comment]
That doesn't work unfortunately, since MyCommand doesn't actually register commands. Just run those 4 commands directly from command blocks! They can be copy-pasted

**Comment by VacAge** [comment]
MyCommand has a command registration option and when I turned it on everything worked, but your plugin still throws an error

**Comment by VacAge** [comment]
> That doesn't work unfortunately, since MyCommand doesn't actually register commands. Just run those 4 commands directly from command blocks! They can be copy-pasted

MyCommand has a command registration option and when I turned it on everything worked, but your plugin still throws an error
![image](https://github.com/Geitenijs/CommandBlocks/assets/55461273/6d8e9d21-53ec-47c8-8533-8ce3f0e12695)

**Comment by VacAge** [comment]
I ask you to fix the error that is being issued in vain, as the command is being executed, but I would not like to constantly see the error

**Comment by Geitenijs** [comment]
Post your full blocks.yml file, there might be some other issue going on here

**Comment by VacAge** [comment]
```
chest_trap_1:
  location: -7395#24#-4875#World-Excalibur
  success:
    commands:
      console:
      - /chest_trap_1
  permission:
    value: excalibur.chest.trap
    messages:
    - '&cYou don`t have perms'

```
